name: Build

on: [push, pull_request]

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
 
    - name: Checkout
    - uses: actions/checkout@v1

    - name: Setup .NET Core 3.1
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.0.100

    - name: Build with dotnet
      run: dotnet build src/Xylox.sln --configuration Release
